# Generated by Django 4.1.2 on 2022-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
